package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.Driver;
import meeting.meetingv1.pojo.DriverExample;
import meeting.meetingv1.pojo.DriverKey;

import java.util.List;

public interface DriverMapper {
    //将分配标记置为0，表示可用个数为0
    public void assignDriverFlagByPrimaryKey(DriverKey driverKey);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DriverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int insertSelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    List<Driver> selectByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    Driver selectByPrimaryKey(DriverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Driver record);
}