package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.Meetinfo;
import meeting.meetingv1.pojo.MeetinfoExample;

import java.util.List;

public interface MeetinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer meetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    int insert(Meetinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    int insertSelective(Meetinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    List<Meetinfo> selectByExample(MeetinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    Meetinfo selectByPrimaryKey(Integer meetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Meetinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Meetinfo record);
}