package meeting.meetingv1.mapper;

import java.util.List;
import meeting.meetingv1.pojo.MeetingSignInTable;
import meeting.meetingv1.pojo.MeetingSignInTableExample;

public interface MeetingSignInTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer meetingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    int insert(MeetingSignInTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    int insertSelective(MeetingSignInTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    List<MeetingSignInTable> selectByExample(MeetingSignInTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    MeetingSignInTable selectByPrimaryKey(Integer meetingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeetingSignInTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MeetingSignInTable record);
}