package meeting.meetingv1.mapper;

import java.util.List;
import meeting.meetingv1.pojo.MeetingSignInUser;
import meeting.meetingv1.pojo.MeetingSignInUserExample;
import meeting.meetingv1.pojo.MeetingSignInUserKey;

public interface MeetingSignInUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(MeetingSignInUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    int insert(MeetingSignInUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    int insertSelective(MeetingSignInUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    List<MeetingSignInUser> selectByExample(MeetingSignInUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    MeetingSignInUser selectByPrimaryKey(MeetingSignInUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeetingSignInUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MeetingSignInUser record);
}