package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.UserMeeting;
import meeting.meetingv1.pojo.UserMeetingExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface UserMeetingMapper {

    @Select("SELECT COUNT(*) FROM user_meeting WHERE meetingid=#{meetingid} AND type=#{type}")
    int count(Byte type, Integer meetingid);

    @Delete("delete from user_meeting where userid=#{userid} AND meetingid=#{meetingid} AND type=#{type}")
    int delete(UserMeeting userMeeting);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int insert(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int insertSelective(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    List<UserMeeting> selectByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    UserMeeting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMeeting record);

    @Select("select type from user_meeting where userid = #{userId} and meetingid = #{meetingId} and (type = 4 or type = 5 or type = 6)")
    int getVoluntTypeFlag(Integer userId, Integer meetingId);


}