package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.Voluntinfo;
import meeting.meetingv1.pojo.VoluntinfoExample;

import java.util.List;

public interface VoluntinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    int insert(Voluntinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    int insertSelective(Voluntinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    List<Voluntinfo> selectByExample(VoluntinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    Voluntinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Voluntinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Voluntinfo record);
}