package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.Voluntask;
import meeting.meetingv1.pojo.VoluntaskExample;

import java.util.List;

public interface VoluntaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    int insert(Voluntask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    int insertSelective(Voluntask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    List<Voluntask> selectByExample(VoluntaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    Voluntask selectByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Voluntask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voluntask
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Voluntask record);
}