package meeting.meetingv1.mapper;

import meeting.meetingv1.pojo.Volunt;
import meeting.meetingv1.pojo.VoluntExample;
import meeting.meetingv1.pojo.VoluntKey;

import java.util.List;

public interface VoluntMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VoluntKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    int insert(Volunt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    int insertSelective(Volunt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    List<Volunt> selectByExample(VoluntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    Volunt selectByPrimaryKey(VoluntKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Volunt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Volunt record);
}