package meeting.mettingv1.pojo;

public class Guest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.guestid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer guestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer meetingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.avatar_url
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.guestid
     *
     * @return the value of guest.guestid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getGuestid() {
        return guestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.guestid
     *
     * @param guestid the value for guest.guestid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setGuestid(Integer guestid) {
        this.guestid = guestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.meetingid
     *
     * @return the value of guest.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.meetingid
     *
     * @param meetingid the value for guest.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.avatar_url
     *
     * @return the value of guest.avatar_url
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.avatar_url
     *
     * @param avatarUrl the value for guest.avatar_url
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.introduction
     *
     * @return the value of guest.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.introduction
     *
     * @param introduction the value for guest.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}