package meeting.mettingv1.pojo;

public class UserMeeting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.userid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer meetingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.type
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.userid
     *
     * @return the value of user_meeting.userid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.userid
     *
     * @param userid the value for user_meeting.userid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.meetingid
     *
     * @return the value of user_meeting.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.meetingid
     *
     * @param meetingid the value for user_meeting.meetingid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.type
     *
     * @return the value of user_meeting.type
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.type
     *
     * @param type the value for user_meeting.type
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.id
     *
     * @return the value of user_meeting.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.id
     *
     * @param id the value for user_meeting.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}