package meeting.mettingv1.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.psw
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String psw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.groups
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String groups;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.personal_events_id_list
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String personalEventsIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mail
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creattime
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String creattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.psw
     *
     * @return the value of user.psw
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.psw
     *
     * @param psw the value for user.psw
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.groups
     *
     * @return the value of user.groups
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.groups
     *
     * @param groups the value for user.groups
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setGroups(String groups) {
        this.groups = groups == null ? null : groups.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.personal_events_id_list
     *
     * @return the value of user.personal_events_id_list
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getPersonalEventsIdList() {
        return personalEventsIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.personal_events_id_list
     *
     * @param personalEventsIdList the value for user.personal_events_id_list
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setPersonalEventsIdList(String personalEventsIdList) {
        this.personalEventsIdList = personalEventsIdList == null ? null : personalEventsIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mail
     *
     * @return the value of user.mail
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mail
     *
     * @param mail the value for user.mail
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creattime
     *
     * @return the value of user.creattime
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creattime
     *
     * @param creattime the value for user.creattime
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setCreattime(String creattime) {
        this.creattime = creattime == null ? null : creattime.trim();
    }
}