package meeting.mettingv1.pojo;

public class Volunt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.volunt
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer volunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.meetid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer meetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.number
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.isproof
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    private Integer isproof;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.volunt
     *
     * @return the value of volunt.volunt
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getVolunt() {
        return volunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.volunt
     *
     * @param volunt the value for volunt.volunt
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setVolunt(Integer volunt) {
        this.volunt = volunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.meetid
     *
     * @return the value of volunt.meetid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getMeetid() {
        return meetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.meetid
     *
     * @param meetid the value for volunt.meetid
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setMeetid(Integer meetid) {
        this.meetid = meetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.introduction
     *
     * @return the value of volunt.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.introduction
     *
     * @param introduction the value for volunt.introduction
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.number
     *
     * @return the value of volunt.number
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.number
     *
     * @param number the value for volunt.number
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.isproof
     *
     * @return the value of volunt.isproof
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public Integer getIsproof() {
        return isproof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.isproof
     *
     * @param isproof the value for volunt.isproof
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    public void setIsproof(Integer isproof) {
        this.isproof = isproof;
    }
}