package meeting.mettingv1.mapper;

import org.apache.ibatis.annotations.Param;
import pojo.Guest;
import pojo.GuestExample;

import java.util.List;

public interface GuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int countByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int deleteByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int insert(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int insertSelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    List<Guest> selectByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int updateByExample(@Param("record") Guest record, @Param("example") GuestExample example);
}