package meeting.mettingv1.mapper;

import org.apache.ibatis.annotations.Param;
import pojo.UserMeeting;
import pojo.UserMeetingExample;

import java.util.List;

public interface UserMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int countByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int deleteByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int insert(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int insertSelective(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    List<UserMeeting> selectByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMeeting record, @Param("example") UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbggenerated Sat Nov 16 00:42:38 CST 2019
     */
    int updateByExample(@Param("record") UserMeeting record, @Param("example") UserMeetingExample example);
}