package meeting.meetingv1.pojo;

public class DriverKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_id
     *
     * @mbg.generated
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    public DriverKey(Integer driverId, Integer meetingId) {
        this.driverId = driverId;
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    public DriverKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_id
     *
     * @return the value of driver.driver_id
     *
     * @mbg.generated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_id
     *
     * @param driverId the value for driver.driver_id
     *
     * @mbg.generated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.meeting_id
     *
     * @return the value of driver.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.meeting_id
     *
     * @param meetingId the value for driver.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }
}