package meeting.meetingv1.pojo;

public class DriverGuestArengement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_guest_arengement.arg_id
     *
     * @mbg.generated
     */
    private Integer argId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_guest_arengement.driver_id
     *
     * @mbg.generated
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_guest_arengement.guest_id
     *
     * @mbg.generated
     */
    private Integer guestId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_guest_arengement
     *
     * @mbg.generated
     */
    public DriverGuestArengement(Integer argId, Integer driverId, Integer guestId) {
        this.argId = argId;
        this.driverId = driverId;
        this.guestId = guestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_guest_arengement
     *
     * @mbg.generated
     */
    public DriverGuestArengement() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_guest_arengement.arg_id
     *
     * @return the value of driver_guest_arengement.arg_id
     *
     * @mbg.generated
     */
    public Integer getArgId() {
        return argId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_guest_arengement.arg_id
     *
     * @param argId the value for driver_guest_arengement.arg_id
     *
     * @mbg.generated
     */
    public void setArgId(Integer argId) {
        this.argId = argId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_guest_arengement.driver_id
     *
     * @return the value of driver_guest_arengement.driver_id
     *
     * @mbg.generated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_guest_arengement.driver_id
     *
     * @param driverId the value for driver_guest_arengement.driver_id
     *
     * @mbg.generated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_guest_arengement.guest_id
     *
     * @return the value of driver_guest_arengement.guest_id
     *
     * @mbg.generated
     */
    public Integer getGuestId() {
        return guestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_guest_arengement.guest_id
     *
     * @param guestId the value for driver_guest_arengement.guest_id
     *
     * @mbg.generated
     */
    public void setGuestId(Integer guestId) {
        this.guestId = guestId;
    }
}