package meeting.meetingv1.pojo;

public class GuestKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.guestid
     *
     * @mbg.generated
     */
    private Integer guestid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest.meetingid
     *
     * @mbg.generated
     */
    private Integer meetingid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated
     */
    public GuestKey(Integer guestid, Integer meetingid) {
        this.guestid = guestid;
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated
     */
    public GuestKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.guestid
     *
     * @return the value of guest.guestid
     *
     * @mbg.generated
     */
    public Integer getGuestid() {
        return guestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.guestid
     *
     * @param guestid the value for guest.guestid
     *
     * @mbg.generated
     */
    public void setGuestid(Integer guestid) {
        this.guestid = guestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest.meetingid
     *
     * @return the value of guest.meetingid
     *
     * @mbg.generated
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest.meetingid
     *
     * @param meetingid the value for guest.meetingid
     *
     * @mbg.generated
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }
}