package meeting.meetingv1.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MeetingSignInTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public MeetingSignInTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeetingidIsNull() {
            addCriterion("meetingId is null");
            return (Criteria) this;
        }

        public Criteria andMeetingidIsNotNull() {
            addCriterion("meetingId is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingidEqualTo(Integer value) {
            addCriterion("meetingId =", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidNotEqualTo(Integer value) {
            addCriterion("meetingId <>", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidGreaterThan(Integer value) {
            addCriterion("meetingId >", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidGreaterThanOrEqualTo(Integer value) {
            addCriterion("meetingId >=", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidLessThan(Integer value) {
            addCriterion("meetingId <", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidLessThanOrEqualTo(Integer value) {
            addCriterion("meetingId <=", value, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidIn(List<Integer> values) {
            addCriterion("meetingId in", values, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidNotIn(List<Integer> values) {
            addCriterion("meetingId not in", values, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidBetween(Integer value1, Integer value2) {
            addCriterion("meetingId between", value1, value2, "meetingid");
            return (Criteria) this;
        }

        public Criteria andMeetingidNotBetween(Integer value1, Integer value2) {
            addCriterion("meetingId not between", value1, value2, "meetingid");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeIsNull() {
            addCriterion("sign_in_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeIsNotNull() {
            addCriterion("sign_in_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeEqualTo(Date value) {
            addCriterion("sign_in_start_time =", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeNotEqualTo(Date value) {
            addCriterion("sign_in_start_time <>", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeGreaterThan(Date value) {
            addCriterion("sign_in_start_time >", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sign_in_start_time >=", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeLessThan(Date value) {
            addCriterion("sign_in_start_time <", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("sign_in_start_time <=", value, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeIn(List<Date> values) {
            addCriterion("sign_in_start_time in", values, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeNotIn(List<Date> values) {
            addCriterion("sign_in_start_time not in", values, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeBetween(Date value1, Date value2) {
            addCriterion("sign_in_start_time between", value1, value2, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSignInStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("sign_in_start_time not between", value1, value2, "signInStartTime");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeIsNull() {
            addCriterion("special_code is null");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeIsNotNull() {
            addCriterion("special_code is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeEqualTo(String value) {
            addCriterion("special_code =", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeNotEqualTo(String value) {
            addCriterion("special_code <>", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeGreaterThan(String value) {
            addCriterion("special_code >", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeGreaterThanOrEqualTo(String value) {
            addCriterion("special_code >=", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeLessThan(String value) {
            addCriterion("special_code <", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeLessThanOrEqualTo(String value) {
            addCriterion("special_code <=", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeLike(String value) {
            addCriterion("special_code like", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeNotLike(String value) {
            addCriterion("special_code not like", value, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeIn(List<String> values) {
            addCriterion("special_code in", values, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeNotIn(List<String> values) {
            addCriterion("special_code not in", values, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeBetween(String value1, String value2) {
            addCriterion("special_code between", value1, value2, "specialCode");
            return (Criteria) this;
        }

        public Criteria andSpecialCodeNotBetween(String value1, String value2) {
            addCriterion("special_code not between", value1, value2, "specialCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}