package meeting.meetingv1.pojo;

import java.util.Date;

public class Meeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meetingid
     *
     * @mbg.generated
     */
    private Integer meetingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.m_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.close_time
     *
     * @mbg.generated
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.schedule
     *
     * @mbg.generated
     */
    private String schedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.needvolunteer
     *
     * @mbg.generated
     */
    private Integer needvolunteer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbg.generated
     */
    public Meeting(Integer meetingid, String mName, String location, Date startTime, Date closeTime, String introduction, String schedule, Integer needvolunteer) {
        this.meetingid = meetingid;
        this.mName = mName;
        this.location = location;
        this.startTime = startTime;
        this.closeTime = closeTime;
        this.introduction = introduction;
        this.schedule = schedule;
        this.needvolunteer = needvolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbg.generated
     */
    public Meeting() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meetingid
     *
     * @return the value of meeting.meetingid
     *
     * @mbg.generated
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meetingid
     *
     * @param meetingid the value for meeting.meetingid
     *
     * @mbg.generated
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.m_name
     *
     * @return the value of meeting.m_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.m_name
     *
     * @param mName the value for meeting.m_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.location
     *
     * @return the value of meeting.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.location
     *
     * @param location the value for meeting.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.start_time
     *
     * @return the value of meeting.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.start_time
     *
     * @param startTime the value for meeting.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.close_time
     *
     * @return the value of meeting.close_time
     *
     * @mbg.generated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.close_time
     *
     * @param closeTime the value for meeting.close_time
     *
     * @mbg.generated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.introduction
     *
     * @return the value of meeting.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.introduction
     *
     * @param introduction the value for meeting.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.schedule
     *
     * @return the value of meeting.schedule
     *
     * @mbg.generated
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.schedule
     *
     * @param schedule the value for meeting.schedule
     *
     * @mbg.generated
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule == null ? null : schedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.needvolunteer
     *
     * @return the value of meeting.needvolunteer
     *
     * @mbg.generated
     */
    public Integer getNeedvolunteer() {
        return needvolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.needvolunteer
     *
     * @param needvolunteer the value for meeting.needvolunteer
     *
     * @mbg.generated
     */
    public void setNeedvolunteer(Integer needvolunteer) {
        this.needvolunteer = needvolunteer;
    }
}