package meeting.meetingv1.pojo;

public class Meetingtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingtype.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingtype.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingtype
     *
     * @mbg.generated
     */
    public Meetingtype(Integer typeid, String type) {
        this.typeid = typeid;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingtype
     *
     * @mbg.generated
     */
    public Meetingtype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingtype.typeid
     *
     * @return the value of meetingtype.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingtype.typeid
     *
     * @param typeid the value for meetingtype.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingtype.type
     *
     * @return the value of meetingtype.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingtype.type
     *
     * @param type the value for meetingtype.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}