package meeting.meetingv1.pojo;

import java.util.ArrayList;
import java.util.List;

public class MeetinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public MeetinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeetidIsNull() {
            addCriterion("meetid is null");
            return (Criteria) this;
        }

        public Criteria andMeetidIsNotNull() {
            addCriterion("meetid is not null");
            return (Criteria) this;
        }

        public Criteria andMeetidEqualTo(Integer value) {
            addCriterion("meetid =", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidNotEqualTo(Integer value) {
            addCriterion("meetid <>", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidGreaterThan(Integer value) {
            addCriterion("meetid >", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidGreaterThanOrEqualTo(Integer value) {
            addCriterion("meetid >=", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidLessThan(Integer value) {
            addCriterion("meetid <", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidLessThanOrEqualTo(Integer value) {
            addCriterion("meetid <=", value, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidIn(List<Integer> values) {
            addCriterion("meetid in", values, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidNotIn(List<Integer> values) {
            addCriterion("meetid not in", values, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidBetween(Integer value1, Integer value2) {
            addCriterion("meetid between", value1, value2, "meetid");
            return (Criteria) this;
        }

        public Criteria andMeetidNotBetween(Integer value1, Integer value2) {
            addCriterion("meetid not between", value1, value2, "meetid");
            return (Criteria) this;
        }

        public Criteria andOrganizerIsNull() {
            addCriterion("organizer is null");
            return (Criteria) this;
        }

        public Criteria andOrganizerIsNotNull() {
            addCriterion("organizer is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizerEqualTo(String value) {
            addCriterion("organizer =", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerNotEqualTo(String value) {
            addCriterion("organizer <>", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerGreaterThan(String value) {
            addCriterion("organizer >", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerGreaterThanOrEqualTo(String value) {
            addCriterion("organizer >=", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerLessThan(String value) {
            addCriterion("organizer <", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerLessThanOrEqualTo(String value) {
            addCriterion("organizer <=", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerLike(String value) {
            addCriterion("organizer like", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerNotLike(String value) {
            addCriterion("organizer not like", value, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerIn(List<String> values) {
            addCriterion("organizer in", values, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerNotIn(List<String> values) {
            addCriterion("organizer not in", values, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerBetween(String value1, String value2) {
            addCriterion("organizer between", value1, value2, "organizer");
            return (Criteria) this;
        }

        public Criteria andOrganizerNotBetween(String value1, String value2) {
            addCriterion("organizer not between", value1, value2, "organizer");
            return (Criteria) this;
        }

        public Criteria andHostedbyIsNull() {
            addCriterion("hostedby is null");
            return (Criteria) this;
        }

        public Criteria andHostedbyIsNotNull() {
            addCriterion("hostedby is not null");
            return (Criteria) this;
        }

        public Criteria andHostedbyEqualTo(String value) {
            addCriterion("hostedby =", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyNotEqualTo(String value) {
            addCriterion("hostedby <>", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyGreaterThan(String value) {
            addCriterion("hostedby >", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyGreaterThanOrEqualTo(String value) {
            addCriterion("hostedby >=", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyLessThan(String value) {
            addCriterion("hostedby <", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyLessThanOrEqualTo(String value) {
            addCriterion("hostedby <=", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyLike(String value) {
            addCriterion("hostedby like", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyNotLike(String value) {
            addCriterion("hostedby not like", value, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyIn(List<String> values) {
            addCriterion("hostedby in", values, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyNotIn(List<String> values) {
            addCriterion("hostedby not in", values, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyBetween(String value1, String value2) {
            addCriterion("hostedby between", value1, value2, "hostedby");
            return (Criteria) this;
        }

        public Criteria andHostedbyNotBetween(String value1, String value2) {
            addCriterion("hostedby not between", value1, value2, "hostedby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meetinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meetinfo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}