package meeting.meetingv1.pojo;

import java.util.Date;

public class MeetingSignInTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_sign_in_table.meetingId
     *
     * @mbg.generated
     */
    private Integer meetingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_sign_in_table.sign_in_start_time
     *
     * @mbg.generated
     */
    private Date signInStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_sign_in_table.special_code
     *
     * @mbg.generated
     */
    private String specialCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public MeetingSignInTable(Integer meetingid, Date signInStartTime, String specialCode) {
        this.meetingid = meetingid;
        this.signInStartTime = signInStartTime;
        this.specialCode = specialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_sign_in_table
     *
     * @mbg.generated
     */
    public MeetingSignInTable() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign_in_table.meetingId
     *
     * @return the value of meeting_sign_in_table.meetingId
     *
     * @mbg.generated
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign_in_table.meetingId
     *
     * @param meetingid the value for meeting_sign_in_table.meetingId
     *
     * @mbg.generated
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign_in_table.sign_in_start_time
     *
     * @return the value of meeting_sign_in_table.sign_in_start_time
     *
     * @mbg.generated
     */
    public Date getSignInStartTime() {
        return signInStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign_in_table.sign_in_start_time
     *
     * @param signInStartTime the value for meeting_sign_in_table.sign_in_start_time
     *
     * @mbg.generated
     */
    public void setSignInStartTime(Date signInStartTime) {
        this.signInStartTime = signInStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign_in_table.special_code
     *
     * @return the value of meeting_sign_in_table.special_code
     *
     * @mbg.generated
     */
    public String getSpecialCode() {
        return specialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign_in_table.special_code
     *
     * @param specialCode the value for meeting_sign_in_table.special_code
     *
     * @mbg.generated
     */
    public void setSpecialCode(String specialCode) {
        this.specialCode = specialCode == null ? null : specialCode.trim();
    }
}