package meeting.meetingv1.pojo;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgid
     *
     * @mbg.generated
     */
    private Integer msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendfrom
     *
     * @mbg.generated
     */
    private Integer sendfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendto
     *
     * @mbg.generated
     */
    private Integer sendto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.isread
     *
     * @mbg.generated
     */
    private Integer isread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public Message(Integer msgid, Integer sendfrom, Integer sendto, Integer isread, String content) {
        this.msgid = msgid;
        this.sendfrom = sendfrom;
        this.sendto = sendto;
        this.isread = isread;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public Message() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgid
     *
     * @return the value of message.msgid
     *
     * @mbg.generated
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgid
     *
     * @param msgid the value for message.msgid
     *
     * @mbg.generated
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendfrom
     *
     * @return the value of message.sendfrom
     *
     * @mbg.generated
     */
    public Integer getSendfrom() {
        return sendfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendfrom
     *
     * @param sendfrom the value for message.sendfrom
     *
     * @mbg.generated
     */
    public void setSendfrom(Integer sendfrom) {
        this.sendfrom = sendfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendto
     *
     * @return the value of message.sendto
     *
     * @mbg.generated
     */
    public Integer getSendto() {
        return sendto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendto
     *
     * @param sendto the value for message.sendto
     *
     * @mbg.generated
     */
    public void setSendto(Integer sendto) {
        this.sendto = sendto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.isread
     *
     * @return the value of message.isread
     *
     * @mbg.generated
     */
    public Integer getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.isread
     *
     * @param isread the value for message.isread
     *
     * @mbg.generated
     */
    public void setIsread(Integer isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}