package meeting.meetingv1.pojo;

public class UserMeeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.meetingid
     *
     * @mbg.generated
     */
    private Integer meetingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    public UserMeeting(Integer id, Integer userid, Integer meetingid, Byte type) {
        this.id = id;
        this.userid = userid;
        this.meetingid = meetingid;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    public UserMeeting() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.id
     *
     * @return the value of user_meeting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.id
     *
     * @param id the value for user_meeting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.userid
     *
     * @return the value of user_meeting.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.userid
     *
     * @param userid the value for user_meeting.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.meetingid
     *
     * @return the value of user_meeting.meetingid
     *
     * @mbg.generated
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.meetingid
     *
     * @param meetingid the value for user_meeting.meetingid
     *
     * @mbg.generated
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.type
     *
     * @return the value of user_meeting.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.type
     *
     * @param type the value for user_meeting.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }
}