package meeting.meetingv1.pojo;

public class VoluntKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.volunt
     *
     * @mbg.generated
     */
    private Integer volunt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunt.meetid
     *
     * @mbg.generated
     */
    private Integer meetid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    public VoluntKey(Integer volunt, Integer meetid) {
        this.volunt = volunt;
        this.meetid = meetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunt
     *
     * @mbg.generated
     */
    public VoluntKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.volunt
     *
     * @return the value of volunt.volunt
     *
     * @mbg.generated
     */
    public Integer getVolunt() {
        return volunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.volunt
     *
     * @param volunt the value for volunt.volunt
     *
     * @mbg.generated
     */
    public void setVolunt(Integer volunt) {
        this.volunt = volunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunt.meetid
     *
     * @return the value of volunt.meetid
     *
     * @mbg.generated
     */
    public Integer getMeetid() {
        return meetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunt.meetid
     *
     * @param meetid the value for volunt.meetid
     *
     * @mbg.generated
     */
    public void setMeetid(Integer meetid) {
        this.meetid = meetid;
    }
}